apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: norma-secrets
  namespace: norma
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: infisical-store
  target:
    name: norma-secrets
    creationPolicy: Owner
  # data:
  #   - secretKey: DB_PASSWORD
  #     remoteRef:
  #       key: PLACEHOLDER: /norma/production/DB_PASSWORD
  #   - secretKey: API_URL
  #     remoteRef:
  #       key: PLACEHOLDER: /norma/production/API_URL
