apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: norma-secrets
  namespace: norma
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: prod-secret-store
  target:
    name: postgres-secret
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: POSTGRES_PASSWORD
