apiVersion: v1
kind: Secret
metadata:
  name: infisical-credentials
  namespace: norma
type: Opaque
stringData:
  clientId: "<your-infisical-client-id>"
  clientSecret: "<your-infisical-client-secret>"
