apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: prod-secret-store
  namespace: norma
spec:
  provider:
    infisical:
      hostAPI: https://api.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-credentials
            key: clientId
          clientSecret:
            name: infisical-credentials
            key: clientSecret
      secretsScope:
        projectSlug: norma-t-rt-u
        environmentSlug: prod
